app/models.py
#imports 
from datetime import datetime
from app import db, login_manager
from flask_login import UserMixin

#Login Loader
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))




#User Database Model
class User(db.Model,UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(120), nullable=False, unique=True)
    password = db.Column(db.String,nullable=False)
    image_file = db.Column(db.String, nullable=False, default='default.jpeg')
    bio = db.Column(db.String)
    posts = db.relationship('Post', backref='users', lazy=True)


#Post Databse Model
class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    content = db.Column(db.String, nullable=False)
    image_file = db.Column(db.String,nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

app/main/forms.py
#imports
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, TextAreaField,SubmitField
from wtforms.validators import DataRequired, Length


#Post Creation Form
class PostForm(FlaskForm):
    title = StringField("title", validators=[DataRequired(),Length(min=2)],render_kw={"placeholder": "Title"})
    content = TextAreaField("Content", validators=[DataRequired(), Length(min=10)],render_kw={"placeholder": "What is the blog about"})
    picture = FileField('image', validators=[FileAllowed(['jpg','png','jpeg'])])
    submit = SubmitField("Publish")
    
#Form to Update Already existing Forms
class UpdatePost(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Title', validators=[DataRequired()])
    submit = SubmitField('Update')

app/__init__.py
#imports
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import  Bcrypt
from flask_login import LoginManager
from app.config import config_options

#Definations
db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'

#Intialization
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    
    
    from app.auth.routes import auths
    from app.main.routes import main
    from app.errors.handlers import errors
    
    app.register_blueprint(auths)
    app.register_blueprint(main)
    app.register_blueprint(errors)
    
    
    return app

app/main/routes.py
#imports
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import current_user, login_required
from app import db
from app.models import Post
from app.main.forms import UpdatePost,PostForm
from app.auth.utils import save_picture
import urllib.request,json



#Main blueprint intialization
main = Blueprint('main', __name__)



#Home default route
@main.route('/',methods=['GET','POST'])
@main.route('/home',methods=['GET','POST'])
def home():
    
    
    #URL for random quotes displayed in the app
    url = 'http://quotes.stormconsultancy.co.uk/random.json'
    
    #First request
    response1 = urllib.request.urlopen(url)
    data1 = response1.read()
    dict1 = json.loads(data1)
    
    #Second request
    response2 = urllib.request.urlopen(url)
    data2 = response2.read()
    dict2 = json.loads(data2)
    
    #Third Request
    response3 = urllib.request.urlopen(url)
    data3 = response3.read()
    dict3 = json.loads(data3)
    
    #Fourth Request
    response4 = urllib.request.urlopen(url)
    data4 = response4.read()
    dict4 = json.loads(data4)
    
    #Fiveth Request
    response5 = urllib.request.urlopen(url)
    data5 = response5.read()
    dict5 = json.loads(data5)
    
    #Sixth Request
    response6 = urllib.request.urlopen(url)
    data6 = response6.read()
    dict6 = json.loads(data6)
    
    posts=Post.query.all()
    return render_template('index.html', quote1=dict1, quote2=dict2, quote3=dict3,quote4=dict4,quote5=dict5,quote6=dict6,posts=posts)


@main.route('/create', methods=['GET','POST'])
@login_required
def create():
    form = PostForm()
    if form.validate_on_submit():
        picture_file = save_picture(form.picture.data)
        post = Post(title=form.title.data,content=form.content.data,image_file=picture_file,user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash("Post Created successfully")
        return redirect(url_for('main.home'))
    return render_template('create.html', form=form)




#Individual Post Route
@main.route('/post/<int:post_id>', methods=['GET','POST'])
def post(post_id):
    form = UpdatePost()
    post = Post.query.get(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Post updated successfully")
        return redirect(url_for('main.post',post_id=post.id))
    form.title.data = post.title
    form.content.data = post.content
    return render_template('post.html', post=post, form=form)


#Route to Delete a Post
@main.route('/post/delete/<int:post_id>')
@login_required
def delete(post_id):
    # sourcery skip: remove-unnecessary-else, swap-if-else-branches
    post_to_delete = Post.query.get(post_id)
    id = current_user.id
    if id == post_to_delete.users.id:
        try:
            db.session.delete(post_to_delete)
            db.session.commit()
            flash("Post deleted successfully")
            return redirect(url_for('main.home'))
        except :
            return redirect(url_for('main.post'))
    else:
        return redirect(url_for('main.home'))
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='images/paper-plane.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css') }}"> {% block head %}{% endblock %}
</head>

<body>
    <section class="header-nav">
        <nav>
            <section class="nav">
                <img src="{{ url_for('static',filename='images/pressly-logo.png') }}" alt="">
                <ul class="nav-menu">
                    <li><a href="{{ url_for('main.home') }}">Home</a></li>
                    {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('users.profile') }}">Profile</a></li>
                    <li><a href="{{ url_for('main.create') }}">Create</a></li>
                    <li class="signup"><a href="{{ url_for('users.logout') }}">Logout</a></li>
                    {% else %}
                    <li><a href="{{ url_for('users.login') }}">Login</a></li>
                    <li class="signup"><a href="{{ url_for('users.register') }}">Sign up</a></li>
                    {% endif %}
                </ul>
                <div class="hamburger">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </div>
            </section>
        </nav>
    </section>
    {% with messages = get_flashed_messages() %} {% if messages %} {% for msg in messages %}
    <div class="flashed" id="flashed">
        <p>{{ msg }}</p>
        <h4 id="closemsg">&times;</h4>
    </div>{% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock %}
    <section class="footer">
        <section class="footer-container">
            <article class="footer-container-created">
                <h3>Crafted with</h3>
                <img src="{{ url_for('static', filename='images/heart.png') }}" alt="heart">
                <h3>By <span>Eugene Oluoch</span></h3>
            </article>
        </section>
    </section>
    <script src="{{ url_for('static',filename='js/nav.js') }}"></script>
    <script src="{{ url_for('static',filename='js/quit.js') }}"></script>
</body>

</html>

app/templates/create.html
{% extends 'base.html' %} {% block head %}
<title>Pressly - Create</title>
<link rel="stylesheet" href="{{ url_for('static',filename='css/login.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='css/create2.css') }}"> {% endblock %} {% block content %}
<section class="header">
    <section class="create" id='create'>
        <form action="" method="post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="create-form-image">
                <img src="{{ url_for('static',filename='images/pressly-logo.png') }}" alt="">
            </div>
            <div>
                {{ form.title }}
            </div>
            <div>
                {{ form.content }}
            </div>
            <div class="create-pic">
                {{ form.picture }}
            </div>
            <div class="create-publish">
                {{ form.submit }}
            </div>
        </form>
    </section>
</section>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/main.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='css/create.css') }}">
<style>
    .none {
        display: none;
    }
</style>
<title>Pressly - Home</title>
{% endblock %} {% block content %}

<section class="main">
    <article class="main-container">
        <article class="first">
            <div>
                <h1>“ {{ quote4.quote }} ”</h1>
                <p>- {{ quote4.author }}</p>
            </div>
        </article>
        <article class="second">
            <div>
                <h1>“ {{ quote5.quote }} ”</h1>
                <p>- {{ quote5.author }}</p>
            </div>
        </article>
        <article class="third">
            <div>
                <h1>“ {{ quote6.quote }} ”</h1>
                <p>- {{ quote6.author }}</p>
            </div>
        </article>
    </article>
    <article class="quotes-title">
        <h1>Daily Dose of Quotes</h1>
    </article>
    <article class="quote-container">
        <article class="first-quote">
            <p>“{{ quote1.quote }}”</p>
            <h3>-<span><a href="{{ quote1.permalink }}" target="_blank">{{ quote1.author }}</a></span></h3>
        </article>
        <article class="second-quote">
            <p>“{{ quote2.quote }}”</p>
            <h3>-<span><a href="{{ quote2.permalink }}" target="_blank">{{ quote2.author }}</a></span></h3>
        </article>
        <article class="third-quote">
            <p>“{{ quote3.quote }}”</p>
            <h3>-<span><a href="{{ quote3.permalink }}" target="_blank">{{ quote3.author }}</a></span></h3>
        </article>
    </article>
    <article class="stories-title">
        <h1>All Stories</h1>
    </article>
    <article class="stories-container">
        {% for post in posts %}
        <article class="first-stories">
            <div class="first-stories-image">
                <img src="{{ url_for('static',filename='images/' + post.image_file) }}" alt="">
            </div>
            <h5 class="flex-those">{{ post.date_posted.strftime('%Y-%m-%d') }}</h5>
            <div class="first-stories-desc">
                <h1 class="link-to-post">{{ post.title }}</h1>
                <p>{{ post.content }}</p>
                <div class="flex-those">
                    <p>By <span>{{ post.users.name }}</span></p>
                    <a href="{{ url_for('main.post',post_id=post.id) }}" class='view'>View</a>
                </div>
            </div>
        </article>
        {% endfor %}
</section>
<script src="{{ url_for('static', filename='js/pop.js') }}"></script>
<script src="{{ url_for('static', filename='js/yea.js') }}"></script>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %} {% block head %}
<title>Pressly - Login</title>
<link rel="stylesheet" href="{{ url_for('static',filename='css/login.css') }}"> {% endblock %} {% block content %}
<section class="header">
    <article class="header-login">
        <div class="header-login-logo">
            <img src="{{ url_for('static', filename='images/pressly-logo.png') }}" alt="">
        </div>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div>
                {{ form.email }}
            </div>
            <div>
                {{ form.password }}
            </div>
            <div class="header-login-form-submit">
                {{ form.submit }}
            </div>
        </form>
        <div class="header-login-signup">
            <h1>Don't have an account?<a href="{{ url_for('users.register') }}">Sign Up</a></h1>
        </div>
    </article>
</section>
{% endblock %}

app/templates/post.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/post.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='css/create.css') }}">
<style>
    .none {
        display: none;
    }
</style>
<title>Pressly - Post</title>
{% endblock %} {% block content %}
<section class="create none" id='create'>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <h1 id="pop">&times;</h1>
        <div class="create-form-image">
            <img src="{{ url_for('static',filename='images/pressly-logo.png') }}" alt="">
        </div>
        <div>
            {{ form.title }}
        </div>
        <div>
            {{ form.content }}
        </div>
        <div class="create-publish">
            {{ form.submit }}
        </div>
    </form>
</section>
<section class="header">
    <article class="header-blog">
        <div class="header-blog-image">
            <img src="{{ url_for('static', filename='images/'+post.image_file) }}" alt="" height="500px">
        </div>
        <div class="header-blog-desc">
            <h4>{{ post.date_posted.strftime('%Y-%m-%d') }}</h4>
            <h1>{{ post.title }}</h1>
            <h3>{{ post.content }}</h3>
            <p>By <span>{{ post.users.name }}</span></p>
        </div>
    </article>
    <div class="btns">
        {% if current_user.id == post.users.id %}
        <button id="btn">update</button>
        <a href="{{ url_for('main.delete',post_id=post.id) }}" class="del">Delete</a> {% endif %}
    </div>
</section>
<script src="{{ url_for('static', filename='js/trying.js') }}"></script>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/profile.css') }}">
<title>Pressly - Profile</title>
{% endblock %} {% block content %}

<section class="header-p">
    <article class="header-profile">
        <div class="header-profile-image">
            <img src="{{ image }}" alt="" width='125px' height='125px'>
        </div>
        <div class="header-profile-desc">
            <h1>{{ current_user.name }}</h1>
            <p>{{ current_user.email }}</p>
        </div>
    </article>
    <article class="header-about">
        <div class="header-about-title">
            <h1>Bio</h1>
        </div>
        <div class="header-about-desc">
            <p>{{ current_user.bio }}</p>
        </div>
    </article>
    <article class="header-update">
        <div class="header-update-title">
            <h1>Account Informantion</h1>
        </div>
        <form action="" method="post" enctype='multipart/form-data'>
            {{ form.hidden_tag() }}
            <div class="header-update-form-name">
                {{ form.name }}
            </div>
            <div class="header-update-form-email">
                {{ form.email }}
            </div>
            <div class="header-update-form-email">
                {{ form.profile_pic }}
            </div>
            <div class="header-update-form-about">
                {{ form.bio }}
            </div>
            <div class="header-update-form-submit">
                {{ form.submit }}
            </div>
        </form>
    </article>
</section>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
<title>Pressly - Register</title>
{% endblock %} {% block content %}
<section class="header">
    <article class="header-login">
        <div class="header-login-logo">
            <img src="{{url_for('static',filename='images/pressly-logo.png')}}" alt="">
        </div>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div>
                {{ form.name }}
            </div>
            <div>
                {{ form.email }} {% if form.email.errors %}{% for error in form.email.errors %}
                <p class="error">{{ error }}</p>
                {% endfor %}{% endif %}
            </div>
            <div>
                {{ form.password }}
            </div>
            <div>
                {{ form.confirm_password }} {% if form.confirm_password.errors %} {% for error in form.confirm_password.errors %}
                <p class="error">{{error}}</p>
                {% endfor %} {% endif %}
            </div>
            <div class="header-login-form-submit">
                {{ form.submit }}
            </div>
        </form>
        <div class="header-login-signup">
            <h1>Already have an account?<a href="{{ url_for('users.login') }}">Login</a></h1>
        </div>
    </article>
</section>

{% endblock %}